### ISSUE TITLE
你好，我想问问你博客头像上面的图片是怎样替换的，是用了这个主题的？

### ISSUE THREAD

**Issue by ruijun** [mrljdx/hexo-theme-yilia-plus#1]
你好，我想问问你博客头像上面的图片是怎样替换的，是用了这个主题的？

**Comment by mrljdx** [comment]
我是直接将图片资源上传到七牛服务器，然后生成外部链接，在yilia-plus的博客配置文件中，将avatar的链接地址改成 生成的那个头像外部链接即可。另外本主题不再维护了，请体验一个不错的主题[NexT](http://theme-next.iissnan.com/)
